name: dea-env
channels:
  - anaconda
  - conda-forge
dependencies:
  - conda-forge::black
  - conda-forge::black-jupyter
  - datacube
  - fpdf
  - geopandas
  - conda-forge::google-api-python-client
  - pytest
  - conda-forge::pytest-cov
  - python=3.10
  - conda-forge::rioxarray
  - anaconda::scikit-image
  - pip:
      - deafrica-tools
      - esbonio
      - sphinx_rtd_theme
