name: Python Package using Micromamba

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - uses: mamba-org/setup-micromamba@v2.0.2
      with:
        environment-file: environment.yml
        init-shell: >-
          bash
        cache-environment: true
        post-cleanup: 'all'

    - name: Run custom command in micromamba environment
      run: >-
        apt-get install sqlite3 
        pytest
      shell: micromamba-shell {0}
