name: PyTest with Micromamba

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        init-shell: >-
          bash
          powershell
        cache-environment: true
        post-cleanup: 'all'
    - name: Run PyTest
      run: pytest
      shell: micromamba-shell {0}
    - name: Run Deps
      run: python tests/deps.py
      shell: micromamba-shell {0}
