name: Python Package using Micromamba

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    # build SQLite from source, because I need 3.35<=
    - run: |
        wget https://sqlite.org/2022/sqlite-autoconf-3380500.tar.gz
        tar -xvf sqlite-autoconf-3380500.tar.gz
    - run: |
        ./configure
        make
        sudo make install
        export PATH="/usr/local/lib:$PATH"
      working-directory: sqlite-autoconf-3380500

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - uses: mamba-org/setup-micromamba@v2.0.2
      with:
        environment-file: environment.yml
        init-shell: >-
          bash
        cache-environment: true
        post-cleanup: 'all'

    - name: Run custom command in micromamba environment
      run: pytest
      shell: micromamba-shell {0}
